# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<image>"
CONTROLLER_HEART_BEAT_EXPIRATION = 30
LOGDIR = "gradio-logs"
WORKER_HEART_BEAT_INTERVAL = 15

MAX_IMAGE_LENGTH = 16
MULTI_IMAGE_TOKEN_1 = "<image 1>"
MULTI_IMAGE_TOKEN_2 = "<image 2>"
MULTI_IMAGE_TOKEN_3 = "<image 3>"
MULTI_IMAGE_TOKEN_4 = "<image 4>"
MULTI_IMAGE_TOKEN_5 = "<image 5>"
MULTI_IMAGE_TOKEN_6 = "<image 6>"
MULTI_IMAGE_TOKEN_7 = "<image 7>"
MULTI_IMAGE_TOKEN_8 = "<image 8>"
IMAGE_TOKEN_INDEX_1 = -201
IMAGE_TOKEN_INDEX_2 = -202
IMAGE_TOKEN_INDEX_3 = -203
IMAGE_TOKEN_INDEX_4 = -204
IMAGE_TOKEN_INDEX_5 = -205
IMAGE_TOKEN_INDEX_6 = -206
IMAGE_TOKEN_INDEX_7 = -207
IMAGE_TOKEN_INDEX_8 = -208